name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Configure Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Code linter
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        cd src
        pylint `ls -R | grep .py$ | xargs`

  build-docker:
    needs: code-analysis
    runs-on: ubuntu-latest
    env:
      MICRO_SERVICE_VERSION: "3.0"

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/pamiel/books-catalog:${{ env.MICRO_SERVICE_VERSION }}-${GITHUB_RUN_NUMBER}
