name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
            --tag docker.io/pamiel/books-catalog:3.0
